Restore bootstrap by removing unused variable in tree-ssa-loop-ivcanon.cc
This restores bootstrap by removing the variable causing:

  /home/mjambor/gcc/trunk/src/gcc/tree-ssa-loop-ivcanon.cc: In function ‘bool try_peel_loop(loop*, edge, tree, bool, long int)’:
  /home/mjambor/gcc/trunk/src/gcc/tree-ssa-loop-ivcanon.cc:1170:17: error: variable ‘entry_count’ set but not used [-Werror=unused-but-set-variable]
   1170 |   profile_count entry_count = profile_count::zero ();
        |                 ^~~~~~~~~~~
  cc1plus: all warnings being treated as errors

gcc/ChangeLog:

2023-07-17  Martin Jambor  <mjambor@suse.cz>

	* tree-ssa-loop-ivcanon.cc (try_peel_loop): Remove unused variable
	entry_count.