c++ modules: static var in inline function [PR104433]
The below testcase fails to link with the error

  undefined reference to `f()::y'

ultimately because during stream out for the static VAR_DECL y we
override DECL_EXTERNAL to true, which later during IPA confuses
symbol_table::remove_unreachable_nodes into thinking it's safe
to not emit the symbol.

The streaming code here already avoids overriding DECL_EXTERNAL for
inline vars and functions, so it seems natural to extend this to
static vars from an inline function.

	PR c++/104433

gcc/cp/ChangeLog:

	* module.cc (trees_out::core_bools): Don't override
	DECL_EXTERNAL to true for static variables from an inline
	function.

gcc/testsuite/ChangeLog:

	* g++.dg/modules/static-2_a.H: New test.
	* g++.dg/modules/static-2_b.C: New test.