testsuite: fix target for linkage-1.C
This test fails in C++11 due to:

linkage-1.C:3:8: error: 'f' function uses 'auto' type specifier without trailing return type
    3 | inline auto f() {
      |        ^~~~
linkage-1.C:3:8: note: deduced return type only available with '-std=c++14' or '-std=gnu++14'

Compile it in C++14 thus.

gcc/testsuite/ChangeLog:

	* g++.dg/cpp2a/linkage-1.C: Use target c++14.