testsuite: Skip btf-bitfields-1.c if int is less than 32-bits
This test spuriously fails on AVR with:
   error: width of 'bitfield_c' exceeds its type

8-bit and 16-bit microcontrollers do not seem to be the target audience
for BTF file format.  So the least intrusive fix is to simply skip the
test for them.

gcc/testsuite/ChangeLog:

	* gcc.dg/debug/btf/btf-bitfields-1.c: Skip if int is less than
	32-bits.

Signed-off-by: Dimitar Dimitrov <dimitar@dinux.eu>