RISC-V: Move vector-abi testcases into rvv/base folder
Resolves failures like this on rv32gcv linux:
compiler exited with status 1
output is:
In file included from /tc-baseline/build-linux-gcv/sysroot/usr/include/features.h:515,
                 from /tc-baseline/build-linux-gcv/sysroot/usr/include/bits/libc-header-start.h:33,
                 from /tc-baseline/build-linux-gcv/sysroot/usr/include/stdint.h:26,
                 from /tc-baseline/build-linux-gcv/lib/gcc/riscv32-unknown-linux-gnu/14.0.0/include/stdint.h:9,
                 from /tc-baseline/build-linux-gcv/build-gcc-linux-stage2/gcc/include/stdint.h:9,
                 from /tc-baseline/build-linux-gcv/build-gcc-linux-stage2/gcc/include/riscv_vector.h:28,
                 from /tc-baseline/gcc/gcc/testsuite/gcc.target/riscv/vector-abi-1.c:4:
/tc-baseline/build-linux-gcv/sysroot/usr/include/gnu/stubs.h:17:11: fatal error: gnu/stubs-lp64d.h: No such file or directory
compilation terminated.

Tested using:
rv{32/64}{gc/gcv} newlib
rv{32/64}gcv linux

gcc/testsuite/ChangeLog:

	* gcc.target/riscv/vector-abi-1.c: Moved to...
	* gcc.target/riscv/rvv/base/vector-abi-1.c: ...here.
	* gcc.target/riscv/vector-abi-2.c: Moved to...
	* gcc.target/riscv/rvv/base/vector-abi-2.c: ...here.
	* gcc.target/riscv/vector-abi-3.c: Moved to...
	* gcc.target/riscv/rvv/base/vector-abi-3.c: ...here.
	* gcc.target/riscv/vector-abi-4.c: Moved to...
	* gcc.target/riscv/rvv/base/vector-abi-4.c: ...here.
	* gcc.target/riscv/vector-abi-5.c: Moved to...
	* gcc.target/riscv/rvv/base/vector-abi-5.c: ...here.
	* gcc.target/riscv/vector-abi-6.c: Moved to...
	* gcc.target/riscv/rvv/base/vector-abi-6.c: ...here.
	* gcc.target/riscv/vector-abi-7.c: Moved to...
	* gcc.target/riscv/rvv/base/vector-abi-7.c: ...here.
	* gcc.target/riscv/vector-abi-8.c: Moved to...
	* gcc.target/riscv/rvv/base/vector-abi-8.c: ...here.
	* gcc.target/riscv/vector-abi-9.c: Moved to...
	* gcc.target/riscv/rvv/base/vector-abi-9.c: ...here.

Reviewed-by: Palmer Dabbelt <palmer@rivosinc.com>
Signed-off-by: Patrick O'Neill <patrick@rivosinc.com>